const FoodProducts=[
  {
    id:100,
    name:"Coffee",
    desc:"A day with one cup of hot tea",
    type:"Morning",
    imgUri:"images/m1.jpg",
    price:"1.5$",
  },
  {
    id:101,
    name:"Coffee & Toast",
    desc:"Morning food with tea & egg.",
    type:"Morning",
    imgUri:"images/1.jpg",
    price:"2.50$",
  },
  {
    id:102,
    name:"Samurai-Chips",
    desc:"tasty Chutney & Chips",
    type:"Morning",
    imgUri:"images/2.jpeg",
    price:"3.00$",
  },
  {
    id:103,
    name:"Pizza",
    desc:"A delicious pizza 🍕",
    type:"Noon",
    imgUri:"images/3.jpeg",
    price:"5.00$",
  },
  {
    id:104,
    name:"Fish Chau",
    desc:"An India food fish-chau.",
    type:"Noon",
    imgUri:"images/8.jpeg",
    price:"10.00$",
  },
  {
    id:105,
    name:"Chicken Biriyani",
    desc:"Delhi super Chicken 🐔 biriyani.",
    type:"Noon",
    imgUri:"images/l1.jpg",
    price:"5.00$",
  },
  {
    id:106,
    name:"Vegetable Salads",
    desc:"Enjoy your evening with Salads.",
    type:"Evening",
    imgUri:"images/6.jpeg",
    price:"2.50$",
  },
  {
    id:107,
    name:"Pasta",
    desc:"chili pasta 🍝.",
    type:"Evening",
    imgUri:"images/4.jpeg",
    price:"1.00$",
  },
  {
    id:108,
    name:"Rice & Chicken-Pop",
    desc:"Summer chicken lolipop.",
    type:"Night",
    imgUri:"images/d1.jpeg",
    price:"5.00$",
  },
  {
    id:109,
    name:"Double 🥚 Egg Bread 🥪.",
    desc:"Egg and bread.",
    type:"Night",
    imgUri:"images/d2.jpeg",
    price:"2.00$",
    
  },
 ];
 
 export default FoodProducts;